cors:
  allowed-methods: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
    health-check-url-path: ${management.context-path}/health
    status-page-url-path: ${management.context-path}/info

management:
  context-path: /management
  security:
    enabled: false              

server:
  compression:
    enabled: true
    mime-types:
      - text/xml
      - application/xml
      - application/json

spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

